### ISSUE TITLE
Rearrange order of commands

### ISSUE THREAD

**Issue by TfTHacker** [kometenstaub/customizable-page-header-buttons#10]
It would be nice to be able to change the order of commands I have added with drag and drop.

**Comment by kometenstaub** [comment]
That would certainly be a great feature.

Do you have an example where another plugin does something like this? (Does Quickadd have something like that maybe?)

**Comment by TfTHacker** [comment]
Quick Add has something for sorting.

I would keep it simple. Add some buttons with up an down arrows, so doens't even need to be drag and drop for changing the order.
