### ISSUE TITLE
Option to change page header font

### ISSUE THREAD

**Issue by davebhc71** [kometenstaub/customizable-page-header-buttons#12]
Would be nice to have an option to change the Note’s Title font to accommodate for viewing text as more items are added by the plugin. Love the plugin!

**Comment by kometenstaub** [comment]
I think the best way to do this is by adding a CSS snippet.

On desktop, the system fonts can be accessed, but on mobile all the theme developers include the fonts as base64 string in the CSS.

With a snippet you can include the font you want to use:

> All you have to do is take your font file and upload it here: [Transfonter.org](https://transfonter.org/). Toggle on `Base64 encode` and hit convert. It will generate a kit for you with a `style.css` file. Open that file and you should see an `@font-face` for your font. Add this to your snippet.
*From Chetachi on Discord with small changes*

And then add this to the snippet, just change `Inter` with the name of your font:

```css
.view-header-title {
    font-family: "Inter";
}
```
