### ISSUE TITLE
wow amazing, but seem to mess with my YAML header files, anyway to fix that?

### ISSUE THREAD

**Issue by zeltak** [kometenstaub/customizable-page-header-buttons#14]
Hi!

this is an amazing plugin! been doing it for months manually until i discovered this :D

one issue i see is that i use YAML headers (which i do ), it sees to mess up the file by adding the header on top of the YAML header (even thought there is a title below YAML), ie:

![image](https://user-images.githubusercontent.com/498410/145534537-c1086129-d812-4582-8fda-85859769b1dc.png)

anyway this can be fixed since all my thousands of files have YAML headers :D

thx!

Z

**Comment by kometenstaub** [comment]
This plugin only adds buttons to the page header, it never touches the editor or the files. Did you mean to write that bug report for another plugin?

**Comment by zeltak** [comment]
oops yeah sorry about the noise :)
