### ISSUE TITLE
[Feature Request 😅] Customizable Titlebar

### ISSUE THREAD

**Issue by jsmorabito** [kometenstaub/customizable-page-header-buttons#15]
I would really like to have the ability to add commands to the titlebar in the same way that this plugin functions. I'm assuming you could copy over most or all of the functionality of this plugin with the only addition being the ability to choose where the command is added in the titlebar since there is the option of appending to `titlebar-button-container mod-left` and `titlebar-button-container mod-right` ... maybe even the titlebar text div in the center? Just an idea I wanted to throw your way! Go ahead and close this issue if its not of interest!

**Comment by kometenstaub** [comment]
I think an extra plugin doesn't make sense for that scenario.

It would mean a duplication of work for all bug fixes/changes that relate to the settings and icon choosing.

There could be another option that is shown when desktop support is enabled to append (`mod-left`) or prepend (`mod-right`) to the title bar.

The logic for that should be simpler than what the plugin does currently. It should only be required to execute that operation onload and another one to remove the chosen button when deleted/all buttons onunload. (Adding buttons to the page header requires a check for every pane.)

It's not something I want to work on at the moment, but could be an addition in the future.

**Comment by jsmorabito** [comment]
Awesome, sounds good!

**Comment by kometenstaub** [comment]
There's a pre-release (3.2.0) that implements this (installable via BRAT), it will be made public in around two weeks, maybe earlier.
