### ISSUE TITLE
[Feature Request] Buttons based on Workspaces

### ISSUE THREAD

**Issue by FelipeRearden** [kometenstaub/customizable-page-header-buttons#26]
My FR is simple to explain: would be amazing if we have a way to define a set of buttons based on different workspaces
- When I use the word **workspace** I mean the Workspace Core Plugin.

In other words, the FR is to be able to define a different set of buttons when I am inside of one specific workspace.

**Comment by kometenstaub** [comment]
This is not something I would implement or accept PRs for. 

Something that might get you there is asking the dev of Workspaces+ to allow different plugin settings for different workspaces and then use that instead of the core workspaces plugin.

**Comment by FelipeRearden** [comment]
👍
