### ISSUE TITLE
Add css snippets as list items

### ISSUE THREAD

**Issue by johans3** [kometenstaub/customizable-page-header-buttons#27]
I would like to select css snippets from the list 

This may sound like.. nothing fancy, but could be a very nice toggle on/off button for some of our favorite snippets
:))

**Comment by kometenstaub** [comment]
There's no need for that. If you use this plugin, you can add snippets as commands and then add buttons for them. https://github.com/deathau/snippet-commands-obsidian

**Comment by johans3** [comment]
Checked, it doesn't add buttons. It adds snippets as cmd to the command palette. That's ok... 

Not to bother you but i need... buttons for my snippets 🤪

**Comment by kometenstaub** [comment]
So the other plugin adds a snippet as a command, and with this plugin this command can be added as a button.

**Comment by johans3** [comment]
my goal is to cut down on plugins as much ad possible, so mixing plugins this way is not really my way
