### ISSUE TITLE
Creates empty leaf when closing file

### ISSUE THREAD

**Issue by dcoales** [kometenstaub/customizable-page-header-buttons#33]
Hi,

When I have this plugin enabled, whenever I close a file (including a hover editor) then an empty pane shows with the words "No file is open".  This is especially annoying if you close a hover editor window then in the main section a new empty leaf appears.  If I disable this plugin this no  longer happens.

I'm currently running 0.15.3 of Obsidian and 4.4.0 of the plugin.

Cheers,
David

**Comment by kometenstaub** [comment]
I cannot reproduce that. Make sure that you are running the latest pane relief version if that plugin is installed.

**Comment by kometenstaub** [comment]
Version 4.5.1 may have fixed it.

**Comment by dcoales** [comment]
Looks like it's fixed.  Thanks.

**Comment by kometenstaub** [comment]
Great news! Thanks for confirming.
