### ISSUE TITLE
Unclosable empty pane created after switching between panes, when all panes pinned

### ISSUE THREAD

**Issue by amandavisconti** [kometenstaub/customizable-page-header-buttons#34]
Thank you @kometenstaub for this very useful plugin!

When I have pinned all my open panes (i.e. right after pinning the last of my unpinned panes), as soon as I click another pane to move focus there, an empty pane appears. This reduces the amount of space to divide among the panes I actually want open (or is distracting as it will reopen if I close it as soon as I move between panes again).

I suspect this behavior may be related to issue #33 ("empty leaf created when closing file").

### Steps to reproduce
1. I have two* panes open. I can change back and forth between them without an empty pane appearing. 
2. I pin one of the two panes. I can change back and forth between them without an empty pane appearing. 
3. I pin the other of the two panes (i.e. I have two panes open; both tabs are pinned). When I click on the other pane to change focus to it, an empty pane appears
4. Clicking the unwanted empty pane's "close file" link closes that unwanted empty pane and switches focus to one of my intentionally-open panes, but as soon as I switch focus to another pane the empty pane appears again (and stays until I close it).

*I tested this with three panes open as well; the unintended empty-pane-opening behavior _does not_ happen if I've only pinned 2 of the 3 panes, and _does_ happen after I've pinned all 3 of the 3 panes, so I suspect this behavior is linked to all open panes being pinned (i.e. set off by pinning of all open panes, rather than by pinning a second pane out of 3+ panes).

Before I started testing what could be causing this, I had something different going on: the same behavior, except clicking the "close" link on the unwanted empty pane did _not_ close the pane, just switched my focus to another pane while leaving the unwanted pane open. I can't reproduce that now, but am noting in case anyone encounters it.

### What I've tried
- Quit and restarted Obsidian
- Used View > Force Reload
- Removed my custom CSS snippets without apparent impact on the issue
- Disabled all other community plugins, did View > Force Reload, no impact on the issue

### My setup
- Core Obsidian, theme (Minimal 5.3.0) and all plugins updated as of 7/3/2022 10am ET
- Obsidian v0.14.15
- Customizable Page Header and Title Bar 4.5.0

I'll report back if I figure out what's causing this, but if anyone has suggestions I'd appreciate them. Thanks!

**Comment by kometenstaub** [comment]
I'll have to investigate.
This behaviour got reported only after 4.4.0 was published, and the only thing I think could cause it is this line:
https://github.com/kometenstaub/customizable-page-header-buttons/blob/01bf997edaa259f59f35c1fcad8294ea71ae9dc0/src/main.ts#L228

I'll try to reproduce later.

Please let me know if you'd run a test build in case I cannot reproduce it (I couldn't repro #33).

**Comment by kometenstaub** [comment]
It is fixed in 4.5.1

**Comment by amandavisconti** [comment]
It is! Thank you very much, I appreciate your looking into this, and also your creating and maintaining this good plugin!
