### ISSUE TITLE
Right click for pane relief navigation registers as a left click

### ISSUE THREAD

**Issue by ronrdev** [kometenstaub/customizable-page-header-buttons#35]
I’ve added back and forward buttons to my page header. I use the pane relief plugin to provide a navigable history on mouse right click. It's been working well. From today. the right click now also registers as a left click. The “dropdown” opens, but the page also changes. I made the update to v0.15.6 earlier and it still worked okay. I noticed the new behavior just after doing plugin update.

Expected behavior: 

Left click navigates one step back or forward.
Right click reveals the known file history from pane relief plugin functionality. And a second click is required before note page changes.

**Comment by kometenstaub** [comment]
Also make sure to use the latest pane relief version.

**Comment by kometenstaub** [comment]
Ok, I can repro.

**Comment by kometenstaub** [comment]
Fixed in 4.6.2.

**Comment by ronrdev** [comment]
Sorry I didn't get a chance to answer right away. I was on latest version of Obsidian, Customizable page header, and Pane Relief. 
Thank you for the fix. Just updated, and checked. I can confirm all is working in my configuration.
