### ISSUE TITLE
Buttons Are Not Showing Up on Title Bars in 0.16.2 

### ISSUE THREAD

**Issue by g1thubth1nk** [kometenstaub/customizable-page-header-buttons#38]
Buttons --corresponding with and representing "Navigate Back" and "Navigate Forward" functions, for instance --aren't showing up on Obsidian's title bars (whether left, right, or center) in Obsidian version 0.16.2 --and this happens despite uninstalling and reinstalling the Plugin, being Customizable Page Header in this case, as well as closing and restarting this new version of Obsidian.

**Comment by kometenstaub** [comment]
That only works with the custom title bar option.
