### ISSUE TITLE
[Feature request] Support for desktop

### ISSUE THREAD

**Issue by jsmorabito** [kometenstaub/customizable-page-header-buttons#6]
Would love to add buttons and also commands to the top bar in the same way that https://github.com/phibr0/obsidian-customizable-sidebar works!

**Comment by kometenstaub** [comment]
I implemented that:
> Would love to add buttons and also commands to the top bar in the same way that https://github.com/phibr0/obsidian-customizable-sidebar works!

If I understand you correctly, you want to use this plugin on desktop as well? I mainly built this because I can't use hotkeys on my phone, but I can also make an option to enable it on desktop.

**Comment by jsmorabito** [comment]
yes!! being able to add icons to that section on desktop would be very useful as well!!

**Comment by jsmorabito** [comment]
you might also consider renaming to "Customizable Page Header" to make the plugin more discoverable in the community plugin browser alongside the "Customizable Sidebar" and "Customizable Menu" plugins (this one should probably be more specific since its about the right click context menu ☺️)

**Comment by kometenstaub** [comment]
Thanks for the tip, I just did so. :)

It works on desktop as well now.
